---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info
    os_server_info:
      cloud: ospcloud
      region_name: RegionOne
    register: openstack_info

  - name: Debug
    debug:
      msg: "Name: {{ instance.name }}"
    loop:
      "{{ openstack_info.openstack_servers }}"
    loop_control:
      loop_var: instance
      label: "{{ instance.name }}"
    when: no

  - name: Delete instances
    os_server:
      cloud: ospcloud
      name: "{{ instance.name }}"
      state: absent
    loop:
      "{{ openstack_info.openstack_servers }}"
    loop_control:
      loop_var: instance
      label: "{{ instance.name }}"
 
# TODO: usar el modulo os_server para borrar las instancias
   
