# Playbook to setup the OpenStack platform with the server instances required for the QA environment

# This play uses the osp-servers role to create the server instances
- hosts: workstation
  become: yes
  gather_facts: no
  roles:
    - osp-servers

