# Playbook to setup workstation and create osp network, router, SG and ssh keypair

# This play creates an in-memory inventory with the correct GUID for the workstation host
- hosts: localhost
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{OSP_GUID}}.rhpds.opentlc.com"
       group: workstation

# This play runs the setup-workstation role, which sets up the worktstation to work with OpenStack
- hosts: workstation
  become: yes
  roles:
    - setup-workstation

# This play runs the playbook: site-install-isolated-node that re-runs the Ansible Tower instalation adding workstation as an isolated node
# This is in order to be able to run workflows from Ansible Tower on OpenStack since only workstation has direct access to the OpenStack controller
- import_playbook: site-install-isolated-node.yml 

