# Playbook to delete the provisioned instances in OpenStack for QA environment

# This play creates an in-memory inventory with the correct GUID for the workstation host
- hosts: localhost
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{OSP_GUID}}.rhpds.opentlc.com"
       group: workstation

- hosts: workstation
  become: yes
  roles:
    - osp-instance-delete

