---

# tasks file for osp.servers
- name: Create new server instances and attaches them a network and passes metadata to the instance
  os_server:
    cloud: ospcloud
    name: "{{ instance.name }}"
    state: "{{ instance.state }}"
    image: "{{ instance.image }}"
    meta: "group={{ instance.meta.group }}, deployment_name={{ instance.meta.deployment_name }}"
    flavor: "{{ instance.flavor }}"
    security_groups: "{{ instance.security_group }}"
    key_name: "{{ instance.key_name }}"
    wait: yes
    nics:
      - net-name: int_network 
    loop: "{{ osp_servers }}"
    loop_control:
      label: "{{ instance }}"

#- name: Add floating IP to Servers
   

#- name: Wait for server to be available

